create extension if not exists pgcrypto;
create extension if not exists vector;

create table if not exists public.profiles (
  id uuid primary key,
  email text unique not null,
  name text not null,
  role text not null default 'student' check (role in ('student', 'faculty', 'admin')),
  picture text,
  clerk_user_id text unique,
  auth_provider text not null default 'supabase',
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  doc_type text not null default 'pdf' check (doc_type in ('pdf', 'docx', 'txt', 'csv', 'pptx', 'json', 'url')),
  filename text not null,
  storage_bucket text not null default 'documents',
  storage_path text,
  file_size bigint not null default 0,
  chunk_count integer not null default 0,
  status text not null default 'pending' check (status in ('pending', 'processing', 'indexed', 'failed')),
  uploaded_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  indexed_at timestamptz,
  error_message text,
  is_seed boolean not null default false,
  seed_origin text,
  category text,
  source_url text,
  verified_on timestamptz,
  total_parts integer not null default 1,
  processing_metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.chat_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.chat_sessions (id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.query_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles (id) on delete set null,
  query text not null,
  response_length integer not null default 0,
  sources_count integer not null default 0,
  voice_input boolean not null default false,
  processing_time_ms integer not null default 0,
  is_web_fallback boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.document_chunks (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references public.documents (id) on delete cascade,
  chunk_index integer not null,
  chunk_text text not null,
  embedding vector(768),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists idx_document_chunks_document_chunk
on public.document_chunks (document_id, chunk_index);

create index if not exists idx_profiles_role on public.profiles (role);
create index if not exists idx_documents_status on public.documents (status);
create index if not exists idx_documents_uploaded_by on public.documents (uploaded_by);
create index if not exists idx_chat_sessions_user_id on public.chat_sessions (user_id);
create index if not exists idx_chat_messages_session_id on public.chat_messages (session_id);
create index if not exists idx_query_logs_user_id on public.query_logs (user_id);
create index if not exists idx_document_chunks_document_id on public.document_chunks (document_id);

create index if not exists idx_document_chunks_embedding
on public.document_chunks
using hnsw (embedding vector_cosine_ops);

do $$
begin
  alter table public.documents
    drop constraint if exists documents_doc_type_check;

  alter table public.documents
    add constraint documents_doc_type_check
    check (doc_type in ('pdf', 'docx', 'txt', 'csv', 'pptx', 'json', 'url'));
end;
$$;

create or replace function public.upsert_document_chunk(
  p_document_id uuid,
  p_chunk_index integer,
  p_chunk_text text,
  p_embedding_text text,
  p_metadata jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
as $$
declare
  v_id uuid;
begin
  insert into public.document_chunks (
    document_id,
    chunk_index,
    chunk_text,
    embedding,
    metadata
  )
  values (
    p_document_id,
    p_chunk_index,
    p_chunk_text,
    p_embedding_text::vector(768),
    coalesce(p_metadata, '{}'::jsonb)
  )
  on conflict (document_id, chunk_index)
  do update set
    chunk_text = excluded.chunk_text,
    embedding = excluded.embedding,
    metadata = excluded.metadata
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.upsert_document_chunk(payload jsonb)
returns uuid
language plpgsql
security definer
as $$
begin
  return public.upsert_document_chunk(
    (payload ->> 'p_document_id')::uuid,
    (payload ->> 'p_chunk_index')::integer,
    payload ->> 'p_chunk_text',
    payload ->> 'p_embedding_text',
    coalesce(payload -> 'p_metadata', '{}'::jsonb)
  );
end;
$$;

create or replace function public.match_document_chunks(
  query_embedding_text text,
  match_count integer default 5,
  match_document_id uuid default null
)
returns table (
  id uuid,
  document_id uuid,
  chunk_index integer,
  chunk_text text,
  metadata jsonb,
  similarity double precision
)
language sql
stable
security definer
as $$
  select
    dc.id,
    dc.document_id,
    dc.chunk_index,
    dc.chunk_text,
    dc.metadata,
    1 - (dc.embedding <=> query_embedding_text::vector(768)) as similarity
  from public.document_chunks dc
  where dc.embedding is not null
    and (match_document_id is null or dc.document_id = match_document_id)
  order by dc.embedding <=> query_embedding_text::vector(768)
  limit greatest(match_count, 1);
$$;

create or replace function public.match_document_chunks(payload jsonb)
returns table (
  id uuid,
  document_id uuid,
  chunk_index integer,
  chunk_text text,
  metadata jsonb,
  similarity double precision
)
language sql
stable
security definer
as $$
  select *
  from public.match_document_chunks(
    payload ->> 'query_embedding_text',
    coalesce((payload ->> 'match_count')::integer, 5),
    case
      when payload ? 'match_document_id' and payload ->> 'match_document_id' <> ''
      then (payload ->> 'match_document_id')::uuid
      else null
    end
  );
$$;

create or replace function public.delete_document_chunks(
  p_document_id uuid
)
returns integer
language plpgsql
security definer
as $$
declare
  deleted_rows integer;
begin
  delete from public.document_chunks
  where document_id = p_document_id;

  get diagnostics deleted_rows = row_count;
  return deleted_rows;
end;
$$;

create or replace function public.delete_document_chunks(payload jsonb)
returns integer
language plpgsql
security definer
as $$
begin
  return public.delete_document_chunks((payload ->> 'p_document_id')::uuid);
end;
$$;

alter table public.profiles enable row level security;
alter table public.documents enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.query_logs enable row level security;
alter table public.document_chunks enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "documents_select_all_authenticated" on public.documents;
create policy "documents_select_all_authenticated"
on public.documents for select
to authenticated
using (true);

drop policy if exists "chat_sessions_manage_own" on public.chat_sessions;
create policy "chat_sessions_manage_own"
on public.chat_sessions for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "chat_messages_manage_own" on public.chat_messages;
create policy "chat_messages_manage_own"
on public.chat_messages for all
to authenticated
using (
  exists (
    select 1
    from public.chat_sessions s
    where s.id = session_id
      and s.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.chat_sessions s
    where s.id = session_id
      and s.user_id = auth.uid()
  )
);

drop policy if exists "query_logs_manage_own" on public.query_logs;
create policy "query_logs_manage_own"
on public.query_logs for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

grant usage on schema public to anon, authenticated, service_role;

grant select on public.document_chunks to authenticated, service_role;
grant insert, update, delete on public.document_chunks to service_role;

grant execute on function public.upsert_document_chunk(uuid, integer, text, text, jsonb) to service_role;
grant execute on function public.upsert_document_chunk(jsonb) to service_role;

grant execute on function public.match_document_chunks(text, integer, uuid) to authenticated, service_role;
grant execute on function public.match_document_chunks(jsonb) to authenticated, service_role;

grant execute on function public.delete_document_chunks(uuid) to service_role;
grant execute on function public.delete_document_chunks(jsonb) to service_role;

notify pgrst, 'reload schema';
